### ISSUE TITLE
Add either a Makefile or CMakeLists.txt build

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/pong#2]
Am initially releasing for POSIX/Linux/Unix/BSD.

Add a Makefile and/or CMakeLists.txt for this game

**Comment by manhtoanbkhn** [comment]
Hello, I'm just add a CMakeLists.txt file and fix some minor issue. The project now can build successfully, but when I run it, I only get log: 
Avg FPS: 58
Unable to render text surface. SDL_ttf error: Passed a NULL pointer
Unable to render text surface. SDL_ttf error: Passed a NULL pointer
Unable to render text surface. SDL_ttf error: Passed a NULL pointer
Unable to render text surface. SDL_ttf error: Passed a NULL pointer
Failed to change _scoresTexture texture

Is there is normal behavior or I'm missing something?

**Comment by gbowne1** [comment]
This game program is incomplete, but as far as I know thats about where I left off in the development and I was having the same issue.  

Can you commit and push up your changes in a PR, I can look at it and see.  @manhtoanbkhn   

There is a bunch of stuff missing.  This game requires the SDL library.. which I am still learning.

**Comment by manhtoanbkhn** [comment]
Yes sure, I want to learn this lib too, nice to contribute to this game. I created a PR, please check it.

**Comment by gbowne1** [comment]
Thanks! I will check it out.
